import { DamageType } from './combat.model';
import { DiceType } from './stats.model';

export interface Action {
  actionId: number;
  name: string;
  description?: string; // Optional: can be provided by backend or generated by UI
  rechargeValue: number;
  hasDC: boolean;
  index: number;
  numberOfDice: number;
  die: DiceType;
  amountToAdd: number;
  attackBonus: number;
  damageType: DamageType;
  dcAbility?: string;
  dcOnSuccess?: string;
  dc?: number;
}

export interface MultiattackOption {
  actionId: number;
  count: number;
}

export interface LegendaryAction {
  actionId: number;
  cost: number; // typically 1-3
  name: string;
  description: string;
}

export interface MonsterActions {
  actions: Action[];
  multiattacks: MultiattackOption[][];
  legendaryActions: Action[];
  rechargeActions: { [actionId: number]: number };
}
